# Generated by Django 4.2.14 on 2024-12-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customerfeddback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeddback',
            name='name',
            field=models.CharField(default='FEEDBACK', max_length=100),
        ),
    ]
