# Generated by Django 4.2.14 on 2024-12-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customerfeddback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeddback',
            name='name',
        ),
    ]
